services:
  - type: web
    name: volvo-service-intelligence
    env: python
    plan: free
    region: oregon

    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y python3.12 python3.12-venv python3.12-distutils
      python3.12 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      . venv/bin/activate
      gunicorn --worker-class eventlet -w 1 app:app

    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
